service: media-service
frameworkVersion: '4'

provider:
  name: aws
  stage: dev
  runtime: nodejs18.x
  region: eu-west-3
  environment:
    MEDIA_BUCKET: ${self:service}-bucket-${sls:stage}
  # >>> On laisse Serverless créer SA propre HTTP API pour ce service
  httpApi:
    cors: true
    authorizers:
      CognitoJwt:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.eu-west-3.amazonaws.com/eu-west-3_gWu9ypjZR
        audience:
          - 70365oucgois2g1ovaj8dr5vi5
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource: arn:aws:s3:::${self:provider.environment.MEDIA_BUCKET}/*

functions:
  getUploadUrl:
    handler: handler.getUploadUrl
    events:
      - httpApi:
          method: POST
          path: /media/upload-url
          authorizer:
            name: CognitoJwt       # protégé (JWT requis)

  getDownloadUrl:
    handler: handler.getDownloadUrl
    events:
      - httpApi:
          method: GET
          path: /media/download-url    # public

resources:
  Resources:
    MediaBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: media-service-bucket-${sls:stage}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ["*"]
              AllowedMethods: ["GET", "PUT"]
              AllowedOrigins: ["*"]
              MaxAge: 300


